### ISSUE TITLE
Issue in Bot's Code

### ISSUE THREAD

**Issue by amokster88** [bramnijssen/PlexDiscordBot#2] opened 2022-07-03 07:35 UTC
`INFO:root:Updating DB...
WARNING:discord.gateway:Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/plexdiscordbot/bot.py", line 19, in <module>
    bot.run(getenv("PDB_BOT_TOKEN"))
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/plexdiscordbot/events.py", line 21, in on_ready
    db.init(self)
  File "/plexdiscordbot/database.py", line 30, in init
    update_db(events)
  File "/plexdiscordbot/database.py", line 51, in update_db
    plex.fetch_tv_show_item(tv_show_id)
  File "/plexdiscordbot/plex.py", line 21, in fetch_tv_show_item
    return get_tv_shows_lib().fetchItem(key)
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 174, in fetchItem
    data = self._server.query(ekey)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 696, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 551, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 404, in _decode
    data = self._decoder.decompress(data)
  File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 91, in decompress
    ret += self._obj.decompress(data)`

**Comment by amokster88** [comment] 2022-07-03 07:36
I searched the error and came up with this!! https://stackoverflow.com/questions/65881761/discord-gateway-warning-shard-id-none-heartbeat-blocked-for-more-than-10-second

**Comment by amokster88** [comment] 2022-07-04 09:25
is the developer active?

**Comment by bramnijssen** [comment] 2022-07-04 09:30
Yes, the developer is still active 😄. The upcoming days I do not have the time to fix this issue, but I'm planning to look over the code during the summer. You are free to implement the solution and create a pull request if you want to have it fixed on a shorter notice.

**Comment by amokster88** [comment] 2022-07-04 09:33
Ok, thanks for the reply. Appreciate it! I will wait till summer then. Not a programmer myself😅, just always fidgeting in my small homelab!😇

**Comment by bramnijssen** [comment] 2022-07-04 09:35
Ok! Anyways, always nice to hear other people are using my project. I'm aware of some issues with the bot (like sending double subscription notifications after the bot has been running for a couple of days) that I want to look into as well.

**Comment by bramnijssen** [comment] 2022-09-05 15:53
@amokster88  I've updated discord.py to v2. v2 changes the way discord.py handles the asyncio event loop. Please let me know if you still are experiencing this issue after updating. If so, are you able to reproduce it on a clean install? Then send me the instructions on how to do so, since I have personally not encountered this issue before. Could be a personal issue with the database perhaps if I follow the order of logs. Good luck; closing for now.

**Closed as completed** 2022-09-05 15:53 UTC
